### ISSUE TITLE
Input/output ordering issues

### ISSUE THREAD

**Issue by GitHunter0** [dreamRs/shinyvs#10]
Hey folks, `shinyvs` seem to have some input/output ordering issues. It forces the order to be the same as the one in `value` passed to `choices`. For example: 
```
library(shiny)
library(shinyvs)

ui <- fluidPage(

  shinyvs::virtualSelectInput(
    inputId = "vs_inputs",
    label = " ",
    html = TRUE,
    choices = data.frame(label = c("val4","val3","val2","val1"),
                         value = c(4, 3, 2, 1)) |> purrr::transpose(),
    selected = c(2,4,3),
    multiple=TRUE,
    search = TRUE,
    position = "top right", 
    disableSelectAll = TRUE
  ),

  verbatimTextOutput("selected_items")
)

server <- function(input, output, session){
  output$selected_items <- renderText({input$vs_inputs})
}

shiny::shinyApp(ui, server)
```

Instead of outputting `2, 4, 3` which is the order passed to `selected`, it returns `4, 3, 2`, as shown in the figure above:
![image](https://user-images.githubusercontent.com/26294221/152613561-465bb975-bdde-4bd9-9ae5-eace580c85b0.png)

Also, the labels in the tooltip are being automatically reordered as well, while I believe it is important to follow the order the user selected (unless specified otherwise), which is the standard. Is there an option to do that? I could not find one.

Another detail is that the output order actually follows the input order selected later interactively but not the initial selected order passed to `selected`.

As an aside,  `position` and `disableSelectAll` parameters seem to have no effect. Am I missing something here or do you want me to open separate issues for that?

Thank you

**Comment by pvictor** [comment]
If order is important in your choices selection, it should be explicit in your design / UI, at least that's what I think.
After the order here is a concern for the JavaScript library: https://github.com/sa-si-dev/virtual-select, I just pass the parameters.

For disableSelectAll parameter:

First of all it only work if `multiple = TRUE` and it makes appear a button to select all values:

![image](https://user-images.githubusercontent.com/4415580/152652323-bcd48d05-0d99-4afc-8bd0-304b5585352c.png)

![image](https://user-images.githubusercontent.com/4415580/152652306-0377994c-7790-4b3d-acd9-5daead6a8004.png)


Indeed `position` doesn't seem to do anything.

**Comment by GitHunter0** [comment]
I'm running this code with `multiple=TRUE` and `disableSelectAll = FALSE`:
```
library(shiny)
library(shinyvs)

ui <- fluidPage(

  shinyvs::virtualSelectInput(
    inputId = "vs_inputs",
    label = " ",
    html = TRUE,
    choices = data.frame(label = c("val4","val3","val2","val1"),
                         value = c(4, 3, 2, 1)) |> purrr::transpose(),
    selected = c(2,4,3),
    multiple=TRUE,
    search = TRUE,
    position = "top right", 
    disableSelectAll = FALSE
  ),

  verbatimTextOutput("selected_items")
)

server <- function(input, output, session){
  output$selected_items <- renderText({input$vs_inputs})
}

shiny::shinyApp(ui, server)
```

But the `Select All` button is not appearing to me, here's the image:
![image](https://user-images.githubusercontent.com/26294221/152653714-bb5f2d86-6595-473d-ae85-53f3b0f5d7ce.png)


``` r
sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.29   withr_2.4.3     magrittr_2.0.1  reprex_2.0.1   
#>  [5] evaluate_0.14   highr_0.9       stringi_1.7.6   rlang_1.0.1    
#>  [9] cli_3.1.1       rstudioapi_0.13 fs_1.5.2        rmarkdown_2.11 
#> [13] tools_4.1.1     stringr_1.4.0   glue_1.6.0      xfun_0.29      
#> [17] yaml_2.2.2      fastmap_1.1.0   compiler_4.1.1  htmltools_0.5.2
#> [21] knitr_1.37
```
<sup>Created on 2022-02-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by GitHunter0** [comment]
> After the order here is a concern for the JavaScript library: https://github.com/sa-si-dev/virtual-select, I just pass the parameters.

So I will open an issue there and post here, thank you @pvictor

**Comment by GitHunter0** [comment]
> Another detail is that the output order actually follows the input order selected later interactively but not the initial selected order passed to `selected`.

I added this detail to my post above.

**Comment by pvictor** [comment]
For `disableSelectAll`: the select all option is the checkbox beside the search field

**Comment by GitHunter0** [comment]
> For `disableSelectAll`: the select all option is the checkbox beside the search field

But the `select all` option does not appear to me **anywhere**, I don't know why.

**Comment by GitHunter0** [comment]
> For `disableSelectAll`: the select all option is the checkbox beside the search field

Now I got it what you said, thanks for clarifying the matter.

**Comment by GitHunter0** [comment]
Hey @pvictor , just to share that https://github.com/sa-si-dev/virtual-select/issues/99 solved this issue. When you find time to update `shinyvs`, I will test it and close this. Thank you

**Comment by pvictor** [comment]
shinyvs is up to date with virtual-select-plugin version 1.0.25. Let me know how it works for you.

**Comment by GitHunter0** [comment]
@pvictor man, I appreciate, it's working fine here!

**Comment by GitHunter0** [comment]
Hey @pvictor , https://github.com/sa-si-dev/virtual-select upgraded to 1.0.28. Please could you update `shinyvs` when you have the time?

**Comment by pvictor** [comment]
Updated to 1.0.28 ✔️
