### ISSUE TITLE
Plans for CRAN release

### ISSUE THREAD

**Issue by krystian8207** [dreamRs/shinyvs#12]
Hi! Thank you for developing this great package - it allows to overcome many performance issues in Shiny Apps.

I wonder if you plan to release the package to CRAN?

I plan to release there one of my packages that imports `shinyvs`, so I'll need to wait for `shinyvs` release first.

Please let me know if you know the answer already.
I'd be also happy to contribute to `shinyvs` (doing required checks and fixes) if it helps.

**Comment by pvictor** [comment]
Hello,
I don't have a clear plan yet. I think it would not be complicated to put this package on the CRAN, but on the other hand it would be easier for me to include these features in shinyWidgets.
shinyWidgets don't use packer yet for managing JavaScript assets, but I'm ready to convert the existing widgets as I go along.
Including `virtualSelectInput` in it will be the occasion to start the process.

**Comment by pvictor** [comment]
`virtualSelectInput()` is now available in [shinyWidgets](https://github.com/dreamRs/shinyWidgets), you can make the switch, I'll push on CRAN soon if everythings works smoothly.

**Comment by krystian8207** [comment]
@pvictor Thank you so much. That's great news!
