### ISSUE TITLE
Labels with HTML

### ISSUE THREAD

**Issue by GitHunter0** [dreamRs/shinyvs#6]
Hey folks, this package is awesome! It is something that I really need in my current project.

I think the one crucial thing that I didn't manage to do was to include HTML in the labels, something like this:

```
library(shiny)
library(shinyvs)

ui <- fluidPage(
  tags$h2("Virtual Select example"),
  
  virtualSelectInput(
    inputId = "single",
    label = "Single select (with 97310 choices) :",
    choices = list(label=c("A <br> second row info",
                           "B <br> second row indo"), 
                   value=1:2) |> purrr::transpose(),
    search = TRUE
  ),
  verbatimTextOutput("res_single")
)

server <- function(input, output, session) {
  output$res_single <- renderPrint(input$single)
}

shinyApp(ui, server)
```
Here I'm trying to make labels with more than one row.

Any help will be much appreciated.

**Comment by pvictor** [comment]
Be sure to have the last version installed, then you can use `virtualSelectInput(..., html = TRUE)`. 
Note that there's a builtin option to add a description line:

```r
library(shiny)
library(shinyvs)

choices <- data.frame(
  label = c("A", "B"),
  value = c(1, 2),
  description = c("More info", "More info")
)

ui <- fluidPage(
  tags$h2("Virtual Select example"),
  
  virtualSelectInput(
    inputId = "single",
    label = "Single select :",
    choices = choices |> 
      prepare_choices(label, value, description = description),
    search = TRUE,
    hasOptionDescription = TRUE
  ),
  verbatimTextOutput("res_single")
)

server <- function(input, output, session) {
  output$res_single <- renderPrint(input$single)
}

shinyApp(ui, server)
```

**Comment by GitHunter0** [comment]
Man, you guys are the best! `shinyvs` is spectacular, it is everything I was needing. Thanks a lot for sharing this package to the community.

@pvictor , any plans to submit to CRAN? It's already working pretty well here.

**Comment by pvictor** [comment]
Including this in shinyWidgets would be the easiest way to reach CRAN I think

**Comment by GitHunter0** [comment]
> Including this in shinyWidgets would be the easiest way to reach CRAN I think

For sure, it is a great idea!
