### ISSUE TITLE
Problem when there is only one group member (updateVirtualSelect also problem)

### ISSUE THREAD

**Issue by daeyoonlee** [dreamRs/shinyvs#7]
Thank you for the fantastic package.
There seems to be a problem with dropdown when there is only one group member. The names are separated.

![image](https://user-images.githubusercontent.com/68131229/151681244-6ec57b17-35fe-429d-af95-e6762d940f0d.png)

![image](https://user-images.githubusercontent.com/68131229/151681203-9b46b99d-bf26-49f0-b7da-70d75df19baf.png)

```
library(shiny)
library(shinyvs)

ui <- fluidPage(
  tags$h2("Virtual Select example"),
  
  choices <- list(Human = c("Han Solo","Darth Vader","Luke Skywalker"), Robot = "R2-D2", Etc = c("Chewbacca","Boba Fett"))
  
  virtualSelectInput(
    inputId = "single",
    label = NULL,
    choices = choices,
    search = TRUE
  ),
  verbatimTextOutput("res_single")
)

server <- function(input, output, session) {
  output$res_single <- renderPrint(input$single)
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Indeed, thanks for reporting, should be better if you re-install from GitHub!

**Comment by daeyoonlee** [comment]
Thank you for answer. However, installing the latest development version today did not solve the problem. What am I missing?

![image](https://user-images.githubusercontent.com/68131229/151888482-09612ea3-083a-4f61-9f07-17ffe60ebb60.png)


```
library(shiny)
library(shinyvs)

choices <- list(Human = c("Han Solo","Darth Vader","Luke Skywalker"), Robot = "R2-D2", Etc = c("Chewbacca","Boba Fett"))

ui <- fluidPage(
  tags$h2("Virtual Select example"),
  
  virtualSelectInput(
    inputId = "single",
    label = NULL,
    choices = choices,
    search = TRUE
  ),
  verbatimTextOutput("res_single")
)

server <- function(input, output, session) {
  output$res_single <- renderPrint(input$single)
}

shinyApp(ui, server)
```

**Comment by daeyoonlee** [comment]
I tried to try packer, but I'm having a hard time figuring out how. Can you guide me? I am using ubuntu and rstudio server.

![image](https://user-images.githubusercontent.com/68131229/151894533-d8ce765d-b88c-413d-b330-d47f4840610e.png)

**Comment by pvictor** [comment]
It works fine for me, are you sure to have last version, if you use `sessioninfo::package_info()` you should see:

```r
sessioninfo::package_info()
#> package     * version    date (UTC) lib source
#> ...
#> shinyvs     * 0.0.0.9200 2022-02-01 [1] Github (dreamRs/shinyvs@196ab53)
#> ...
```

{packer} is only needed if you modify JavaScript code and need to rebundle assets.

**Comment by daeyoonlee** [comment]
Yes. Solved. There was a problem because the previous version was duplicated without being erased.

![image](https://user-images.githubusercontent.com/68131229/151976347-235be04e-5a17-4904-bb2c-de5e16b7692f.png)

**Comment by daeyoonlee** [comment]
`updateVirtualSelect` seems to still have the same issue.

shinyvs            * 0.0.0.9200 2022-02-01 [1] Github (dreamRs/shinyvs@196ab53)

```
library(shiny)
library(shinyvs)

choices <- list(Human = c("Han Solo","Darth Vader","Luke Skywalker"), Robot = "R2-D2", Etc = c("Chewbacca","Boba Fett"))

ui <- fluidPage(
  tags$h2("Virtual Select example"),
  
  virtualSelectInput(
    inputId = "single",
    label = NULL,
    choices = "",
    search = TRUE
  ),
  verbatimTextOutput("res_single")
)

server <- function(input, output, session) {
  
  updateVirtualSelect(
    session = session,
    inputId = "single",
    choices = choices
  )
  output$res_single <- renderPrint(input$single)
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Oups! Thanks for reporting, it's fixed if you re-install from GitHub!

**Comment by daeyoonlee** [comment]
Thank you!
